### ISSUE TITLE
change separator

### ISSUE THREAD

**Issue by nicmare** [jylauril/jquery-runner#1]
found it in the first line:  separator = ['', ':', ':', '.'],
but how can i overwrite it without modifying the sourcecode??

**Comment by jylauril** [comment]
You can use the format option to pass in your own formatter function.

Example:

``` javascript
$('#runner').runner({
    format: function(value, oldFormatter) {
        return (value / 1000) / 60;
    }
});
```

If the format option is provided, it will be used instead of the built-in one.

The first parameter given to that function is the current time in milliseconds and the second parameter is a reference to the old formatter function. So basically you could call the old formatter function from your own custom formatter function and modify the returned string before returning it. Or just write your own. :)

Check the README.md for more info:
https://github.com/jylauril/jquery-runner/blob/master/README.md

**Comment by nicmare** [comment]
hey lauril, thanks for fast answer. but i want to change the format from 15:00.00 to 15:00:00. therefore i have to change the seperator array.

**Comment by jylauril** [comment]
Well of course you can modify the code as you wish.

If you don't want to alter the original code, an ugly hack for your need would be to just replace the dot to a colon:

``` javascript
$('#runner').runner({
    format: function(value, oldFormatter, ms) {
        return oldFormatter(value, ms).replace('.', ':');
    }
});
```
