### ISSUE TITLE
Chrome warning: webkitRequestAnimationFrame' is vendor-specific

### ISSUE THREAD

**Issue by wrburgess** [jylauril/jquery-runner#14]
I see this warning in my Chrome Web Developer Tools when using jquery-runner:

`'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.`

Is this something to be concerned with?

**Comment by jylauril** [comment]
Nah, this is not a problem. Usually when browser vendors implement a new feature that doesn't have a stable specification yet (like requestAnimationFrame in this case), they prefix it with their engine, so it won't cause problems with other browsers.

The jQuery-runner plugin tries to find the best suitable match for the requestAnimationFrame, but it started the search from the webkit-prefixed one, which the Chrome still provides, but they've just added a deprecation warning, as the requestAnimationFrame is becoming more standard now.

I did release a new version that now first checks for the non-vendor specific version of that function, so it should suppress that deprecation warning message now. But even if you don't upgrade the library and Chrome does remove that vendor specific function, it will still work, because it will just try the next possible method name for that, and finally fallback to setTimeout if even that fails. :)

**Comment by wrburgess** [comment]
Thanks for the reply...and the work you do on this plugin!
